/*
 * sdlscrn.c
 *
 * ABC80/802 sound emulation (sn76477 chip)
 */

 /*
  abc80 used a sn76447 chip
  datasheet: https://www.experimentalistsanonymous.com/diy/Datasheets/SN76477.pdf

  circuit from https://www.abc80.net/archive/luxor/ABC80/Mikrodatorns-ABC.pdf

  Is controlled by address 6

  chip coupling
  +---------------------------------------------------+
  | pin   | name             | type        | value    |
  +---------------------------------------------------+
  | 1     | envelope sel 1   | data        | bit7     |
  | 2     | ground           | Vss         |          |
  | 3     | ext.noise clk    | logic       | unused   |
  | 4     | noise clk ctrl   | resistor    | 47k      |
  | 5     | noise filt ctrl  | resistor    | 330k     |
  | 6     | noise filt ctrl  | capacitor   | 390p     |
  | 7     | decay ctrl       | resistor    | 47k      |
  | 8     | attack decay tim | capacitor   | 10u      |
  | 9     | system inhibit   | data        | not bit0 |
  | 10    | attack ctrl      | resistor    | 2.2k     |
  | 11    | amplitude ctrl   | resistor    | 33k      |
  | 12    | feedback res     | resistor    | 10k      |
  | 13    | audio out        | ->          | ->       |
  | 14    | Vcc              | --          | --       |
  | 15    | Vreg             | 5V          | 5V       |
  | 16    | ext.vco ctrl     | volt        | bit1 2V  | (volt divider 1,5k 1k)
  | 17    | vco ctrl         | capacitor   | 10n      |
  | 18    | vco ctrl         | resistor    | 100k     |
  | 19    | pitch ctrl       | volt        | --       |
  | 20    | slf ctrl         | resistor    | 220k     |
  | 21    | slf ctrl         | capacitor   | 1u       |
  | 22    | vco select       | data        | bit2     |
  | 23    | one shot ctrl    | capacitor   | 0.1u     |
  | 24    | one shot ctrl    | resistor    | 330k     |
  | 25    | mixer select B   | data        | bit3     |
  | 26    | mixer select A   | data        | bit4     |
  | 27    | mixer select C   | data        | bit5     |
  | 28    | envelope sel 2   | data        | bit6     |
  +---------------------------------------------------+

  Data register (bits controling what)
  +---------------------------------------------------------------+
  |   7   |   6   |   5   |   4   |   3   |   2   |   1   |   0   |
  +---------------+-----------------------+---------------+-------+
  |   envelope    |         mixer         |      vco      | on/off|
  | 00 vco on/off | 000 VCO               | 00 high freq. | 0 off |
  | 01 mixer only | 001 Noise             | 01 low freq.  | 1 on  |
  | 10 one shot   | 010 SLF  (slow)       | 10 SLF control|       |
  | 11 vco toggle | 011 VCO + noise       | 11 SLF control|       |
  |               | 100 SLF + noise       |               |       |
  |               | 101 SLF + VCO         |               |       |
  |               | 110 SLF + VCO + noise |               |       |
  |               | 111 inhibit           |               |       |
  +---------------+-----------------------+---------------+-------+

  # from chip datasheet
  ## super-low frequency oscillator (SLF)
  The SLF is normally operated in the range of 0.1 hertz to 30 hertz, but will operate up to 20 kilohertz. The frequency
  is determined by two external components, the SLF control resistor (RSLF) at pin 20 and the SLF control capacitor
  (Cslf) at pin 21 according to the following equation:

  Equation 1: SLF frequency (Hz) = 0.64/(Rslf * Cslf) at Vreg = 5 V.

  The SLF supplies two signals to other parts of the device. It feeds a 50% duty cycle square wave to the mixer, and it
  feeds a triangular wave to the external VCO or SLF select logic, where, if VCO select (pin 22) is at a high logic level, it
  is fed through to the VCO to modulate the frequency of that oscillator.
  SLF = 0.64/(220k * 1u) = 2,909090909 Hz

  ## voltage-controlled oscillator (VCO)
  The VCO produces a tone output whose frequency is dependent upon the voltage at the input of the VCO. This
  controlling voltage may be either the SLF output described above, or an externally generated signal applied to the
  external VCO control, pin 16. The method of controlling the VCO is selected by the logic level at the VCO select
  (pin 22). With a low logic level applied to VCO select, the VCO frequency is controlled by an external signal applied to
  the external VCO control, pin 16. When a high is applied to the VCO select, the VCO frequency is controlled internally
  by the triangular waveform signal generated by the super-low-frequency oscillator.

  The higher the voltage applied to the VCO (either internally from the SLF or externally applied to pin 16), the lower
  the frequency of the VCO output. An alternate method of applying an external voltage to the VCO input is to do so
  indirectly by applying the controlling voltage to the SLF oscillator control capacitor input, pin 21. In some applications
  this may be more convenient than using the pin 16 input.
  The minimum frequency of the VCO is determined by the VCO controi resistor (RyCO) at pin 18 and the VCO control
  capacitor (CyCO) at pin 17 according to the following equation:

  Minimum VCO frequency (Hz) = 0.64/(Rvco * Cvco) at Vreg = 5v

  The frequency range of the VCO is internally determined at an approximate ratio of 10:1, so the maximum frequency
  of the VCO will be approximately ten times the minimum frequency determined by the external components Rvco and Cvco.

  Min vco = 0.64 / (100k * 10n) = 640 Hz
  Max vco = 640*10 = 6400 Hz

  When the external VCO control (pin 16) is used (VCO select, pin 22, is low), the voltage at the external VCO control
  should range from 0 to 2.35 volts. If this voltage goes above 2.35 volts, the output of the VCO section saturates at a
  high logic level and in turn saturates the output amplifier stage. This may be used as an alternative method of disabling
  the sound output without changing the system inhibit input. The input at the external VCO control may be a dc
  voltage producing a constant tone, or any digital or analog type input to modulate the frequency of the VCO.

  The pitch control (pin 19) varies the duty cycle of the VCO output according to the following equation:
  Equation 3:
    VCO duty cycle = 50 * (voltage at pin 19 / voltage at pin 16) %

  By leaving pin 19 high, a constant 50% duty cycle is achieved. The minimum duty cycle attainable is approximately
  18%. The specific duty cycle applies to constant tones produced by applying a constant de voltage at the external VCO
  control, but the pitch control may be used to aesthetically alter the pitch of any frequency-modulated VCO output
  signals.
  The output of the VCO is a square-wave pulse and is supplied both to the mixer and through the envelope-select logic
  to the envelope generator and modulator.

  VCO duty_l = 50 * (5 / 2) = 125
  VCO duty_h = 50 * (5 / 0.2) = 1250

  ## noise clock
  The noise clock internally generates clock pulses and supplies them to the noise generator. The noise clock resistor
  (pin 4) sets the internal operating current for the noise clock section. The nominal value for this resistor is 47 k2. For
  faster clock rates, a smaller valued resistor may be used. For slower clock rates, a higher valued resistor may be used, but
  it should be limited to a maximum of 100 k2. It may be desirable to use an external noise clock to provide a lower
  frequency noise or a more precise clock rate. This external clock signal should be applied to the external noise clock
  terminal (pin 3), and the noise clock resistor input should be taken to a high logic voltage level. The external clock
  signal should be a 10-volt-maximum peak-to-peak square wave.

  ## noise generator/filter
  The noise generator produces psuedo-random white noise that passes through the noise filter before being applied to
  the mixer. The variable-band-width low-pass filter has its 3-dB rolloff point defined by th e noise filter control resistor
  (RNF) at pin 5 and the noise filter control capacitor (CNF) according to the following equation:

   Equation 4: 3-dB frequency (Hz) = 1.28 / (Rnf * Cnf) at Vreg = 5 V.

  Rnf should have a minimum value of 7.5k in order to limit the current in the noise filter section to a safe operating
  level.

  cutoff = 1.28 / (330k * 390p) = 9945,60994561 Hz

  ## one-shot
  As mentioned in Section 6 above, the one-shot circuit controls momentary sounds, and is triggered by a high-to-low
  logic-level transitión at the system inhibit input (pin 9). The duration of the one-shot is determined by the one-shot
  control resistor (ROS) at pin 24 and the one-shot control capacitor (Cos) at pin 23 according to the following
  equation:
   Equation 5: One-shot duration (seconds) ≈ 0.8 * Ros * Cos at Vreg = 5 V.

   duration = 0.8 * 330k * 0.1u = 0,033 s

  ## attack and decay control
  The attack and decay circuitry alters the rise and fail times of the envelope selected by the envelope select logic. The
  attack/decay timing capacitor (CA/D) at pin 8 is shared by both the attack and decay circuitry. The attack control
  resistor (RA) at pin 10 sets an internal current that charges capacitor CA/D thereby determining the attack (rise) time
  of the envelope. The decay control resistor (RD) at pin 7 determines the discharge rate of cаpacitor СA/D and thus
  determines the decay (fall) time of the envelope. The actual times may be derived from the following equations:

   Equation 6: Attack time (seconds) ≈ RA * CA/D at Vreg = 5 V.
   Equation 7: Decay time (seconds) ≈ RD * CA/D at Vreg = 5 V.

   attack time = 2.2k * 10u = 0,22 s
   decay time = 47k * 10u = 0,47 s

  If mixer only or one-shot has been chosen at the envelope select inputs, the attack ramp begins when the system inhibit
  (pin 9) is taken low. If VCO or VCO with alternating cycles is selected for the envelope, the attack ramps up on each
  positive edge or every other positive edge, respectively, of the VCO frequency. The decay section ramps the sound
  amplitude down as the sound ends. The decay has no effect on the mixer-only function, but for the one-shot, the VCO,
  and the VCO with alternating cycie envelopes, the decay ramp is triggered by each high-to-low transition of the
  envelope and prolongs the sound at a decaying volume.
  Figure 5 shows examples of how a waveform may be modified by varying degrees of attack and decay when the mixer
  output is noise and the one-shot envelope is selected.

 */

#include <SDL.h>
#include <stdlib.h>
#include <time.h>
#include <math.h>

#ifndef PI
#define PI 3.14159265359
#endif

#define SAMPLING_FREQ 44100
  // one shot duration is 0,22s attack 0,033s oneshot 0,47 decay
#define SAMPLE_CYCLE 0.033f
        // 31884  (44100 * 0.723s)
#define SAMPLES_CNT 1456 /*31884*/
#define VOC_SLF_TABLE_CNT SAMPLING_FREQ
#define STD_AMPLITUDE 4996

#define ATTACK_TIME 0.22f
#define ATTACK_INC (1.0f / (ATTACK_TIME * SAMPLING_FREQ))
#define ATTACK_STEPS (ATTACK_TIME * SAMPLING_FREQ)
#define DECAY_TIME 0.47f
#define DECAY_DEC (1.0f / (DECAY_TIME * SAMPLING_FREQ))
#define DECAY_STEPS (DECAY_TIME * SAMPLING_FREQ)
#define ONESHOT_TIME 0.033f
#define ONESHOT_STEPS (ONESHOT_TIME * SAMPLING_FREQ)

#define SLF_FREQ 3.0f
#define VCO_FREQ 640.0f

// bit masks for data byte
#define ENVELOPE_MASK 0xC0
#define ENVELOPE_VCO  0x00
#define ENVELOPE_MIXER 0x40
#define ENVELOPE_ONE_SHOT 0x80
#define ENVELOPE_VCO_TOOGLE 0xC0
#define ENVELOPE_IS(data, check) \
    ((data) & ENVELOPE_MASK) == (check)

#define MIXER_MASK 0x38
#define MIXER_VCO 0x00
#define MIXER_NOISE 0x08
#define MIXER_SLF 0x10
#define MIXER_VCO_NOISE 0x18
#define MIXER_SLF_NOISE 0x20
#define MIXER_SLF_VCO 0x28
#define MIXER_SLF_VCO_NOISE 0x30
#define MIXER_INHIBIT 0x38
#define MIXER_IS(data, check) \
    ((data) & MIXER_MASK) == (check)

#define VCO_MASK 0x06
#define VCO_HIGH_FREQ 0x00
#define VCO_LOW_FREQ 0x02
#define VCO_SLF_1 0x04
#define VCO_SLF_2 0x06
#define VCO_IS(data, check) \
    ((data) & VCO_MASK) == (check)
#define VCO_IS_SLF_CONTROLLED(data) \
    VCO_IS(data, VCO_SLF_1) || VCO_IS(data, VCO_SLF_2)

#define SOUND_ON 0x01
#define SOUND_IS_ON(data) \
    ((data) & SOUND_ON) == SOUND_ON

#define CUTOFF_FREQ 9946

#define next_slf(sdata) \
    ((sdata).SLF_samples[(sdata).slf_pos >= VOC_SLF_TABLE_CNT \
                                    ? ((sdata).slf_pos = 0) \
                                    : ((sdata).slf_pos++)])

#define next_vco(sdata) \
    ((sdata).VCO_samples[(sdata).vco_pos >= VOC_SLF_TABLE_CNT \
                                    ? ((sdata).vco_pos = 0) \
                                    : ((sdata).vco_pos++)])

#define next_attack(sdata) \
    ((sdata).attack < 1.0f ? ((sdata).attack += ATTACK_INC) : 1.0f)

#define next_decay(sdata) \
    ((sdata).decay > 0.0f ? ((sdata).decay -= DECAY_DEC) : 0.0f)

enum one_shot_state_e {
    OneShotArmed,
    OneShotAttack,
    OneShotHold,
    OneShotDecay,
    OneShotDone
};

struct sound_data {
    float SLF_samples[VOC_SLF_TABLE_CNT],
          VCO_samples[VOC_SLF_TABLE_CNT];
    size_t slf_pos,
           vco_pos;
    SDL_AudioSpec *spec;
    SDL_AudioDeviceID device_id;
    float attack, // 0.0-1.0 where 1.0 is full volume
          decay;  // 1.0-0.0 where 1.0 is full volume, 0.0 is decayed
    enum one_shot_state_e one_shot_state;
    union {
        uint8_t data; // the data byte that initiated last command
        uint8_t on: 1; // bit0 of data
        uint8_t vco: 2; // bit1 and bit2 of data (Voltage controlled oscillator)
        uint8_t mixer: 3; // bit3-5 of data mixer selection
        uint8_t envelope: 2; // bit 6-7 of data envelope selection
    };
};
static struct sound_data sdata;

static SDL_mutex *sdata_mutex;

static void attack_decay_from_vco(
    int toggle,
    int16_t* samples,
    size_t *vco_pos,
    size_t len
) {
    int cnt = 0, on = 0;
    const float threshold = (float)(STD_AMPLITUDE / 2);
    for (size_t i = 0; i < len; ++i) {
        if (++(*vco_pos) == VOC_SLF_TABLE_CNT)
            *vco_pos = 0;

        if (sdata.VCO_samples[*vco_pos] > threshold && !on) {
            on = 1;
            cnt += 1;
            if (sdata.attack >= 1.0f)
                sdata.attack = 0.0f;
        } else if (sdata.VCO_samples[*vco_pos] < -threshold && on) {
            on = 0;
            cnt = cnt > toggle ? 0 : 1;
            if (sdata.decay <= 0.0f)
                sdata.decay = 1.0f;
        }
        if (on)
            samples[i] = next_attack(sdata) * samples[i];
        else
            samples[i] = next_decay(sdata) * samples[i];
    }
}

static void attack_decay_one_shot(
    int16_t* samples,
    size_t *one_shot_pos,
    size_t len
) {
    for (size_t i = 0; i < len; ++i) {
        if (sdata.one_shot_state == OneShotArmed && *one_shot_pos == 0) {
            sdata.one_shot_state = OneShotAttack;
            sdata.attack = 0.0f;
        }
        if (*one_shot_pos > (ATTACK_STEPS + ONESHOT_STEPS + DECAY_STEPS)) {
            sdata.one_shot_state = OneShotDone;
            *one_shot_pos = 0;
        } else if (sdata.one_shot_state == OneShotHold && *one_shot_pos > (ATTACK_STEPS + ONESHOT_STEPS)) {
            sdata.one_shot_state = OneShotDecay;
            sdata.decay = 1.0f;
        } else if (sdata.one_shot_state == OneShotAttack && *one_shot_pos > ATTACK_STEPS) {
            sdata.one_shot_state = OneShotHold;
        }


        switch (sdata.one_shot_state) {
        case OneShotDecay:
            samples[i] = next_decay(sdata) * samples[i];
            (*one_shot_pos)++;
            break;
        case OneShotAttack:
            samples[i] = next_attack(sdata) * samples[i];
            // fallthrough
        case OneShotHold:
            (*one_shot_pos)++;
            break;
        case OneShotArmed:
        default:
            samples[i] = 0; // silence
            break;
        }
    }
}

static void audio_callback(void* userdata, Uint8* stream, int length)
{
    (void)userdata;
    SDL_LockMutex(sdata_mutex);

	int16_t* samples = (int16_t*) stream;
	const size_t len = length / sizeof(int16_t);

    switch (sdata.data & MIXER_MASK) {
    case MIXER_VCO:
        for (size_t i = 0; i < len; ++i) {
            samples[i] = next_vco(sdata);
            //printf("%d\n", samples[i]);
        }
        break;
    case MIXER_NOISE:
        for (size_t i = 0; i < len; ++i)
            samples[i] = rand() % STD_AMPLITUDE; // white noise
        break;
    case MIXER_SLF:
        for (size_t i = 0; i < len; ++i)
            samples[i] = next_slf(sdata);
        break;
    case MIXER_VCO_NOISE:
        for (size_t i = 0; i < len; ++i)
            samples[i] = (int16_t)((next_vco(sdata) / STD_AMPLITUDE) * next_slf(sdata));
        break;
    case MIXER_SLF_NOISE:
        for (size_t i = 0; i < len; ++i){
            int16_t rnd = -(STD_AMPLITUDE / 2) + rand() % STD_AMPLITUDE;
            samples[i] = (int16_t)((next_slf(sdata) / STD_AMPLITUDE) * rnd);
        }
        break;
    case MIXER_SLF_VCO:
        for (size_t i = 0; i < len; ++i)
            samples[i] = (int16_t)((next_slf(sdata) / STD_AMPLITUDE) * next_vco(sdata));
        break;
    case MIXER_SLF_VCO_NOISE:
        for (size_t i = 0; i < len; ++i) {
            int16_t rnd = -(STD_AMPLITUDE / 2) + rand() % STD_AMPLITUDE;
            samples[i] = (next_slf(sdata) / STD_AMPLITUDE) * (next_vco(sdata) + rnd);
        }
        break;
    case MIXER_INHIBIT:
    default:
        for (size_t i = 0; i < len; ++i)
            samples[i] = 0;
        break;
    }

    static size_t vco_pos = 0,
                  one_shot_pos = 0;

    switch (sdata.data & ENVELOPE_MASK) {
    case ENVELOPE_VCO:
        attack_decay_from_vco(0, samples, &vco_pos, len);
        break;
    case ENVELOPE_VCO_TOOGLE:
        attack_decay_from_vco(1, samples, &vco_pos, len);
        break;
    case ENVELOPE_ONE_SHOT:
        attack_decay_one_shot(samples, &one_shot_pos, len);
        break;
    case ENVELOPE_MIXER:
    default: break; // straight through
    }

    //printf("Start: %d end: %d\n", samples[0], samples[sample_count-1]);

    SDL_UnlockMutex(sdata_mutex);
}

static void generate_slf()
{
    // triangular wave 2.90Hz in sample in 1s
    static const size_t len = sizeof(sdata.SLF_samples) / sizeof(sdata.SLF_samples[0]);
    float factor = (STD_AMPLITUDE * SLF_FREQ * 4) / len;
    float vlu = 0;
    for (size_t i = 0; i < len; ++i) {
        vlu += factor;
        if (vlu >= STD_AMPLITUDE || vlu <= -STD_AMPLITUDE) {
            factor *= -1;
            //printf("flip");
        }
        sdata.SLF_samples[i] = vlu;
        //printf("slf:%f\n", sdata.SLF_samples[i]);
    }
}

static void generate_vco(int freq_factor)
{
    // generate 1s sine wave high or low freq, low at 640Hz
    static const size_t len = sizeof(sdata.SLF_samples) / sizeof(sdata.SLF_samples[0]);
    double periods = VCO_FREQ * freq_factor;
    double rot_angle = (periods * 2 * PI) / len;
    for (size_t i = 0; i < len; ++i) {
        sdata.VCO_samples[i] = STD_AMPLITUDE * sin(rot_angle * i);
        //printf("%f\n", sdata.VCO_samples[i]);
    }
}

static void generate_internal_vco(int freq_factor)
{
    // generate 1s sine wave high or low freq, low at 640Hz
    static const size_t len = sizeof(sdata.SLF_samples) / sizeof(sdata.SLF_samples[0]);

    double periods = VCO_FREQ * freq_factor;
    double rot_angle = (periods * 2 * PI) / len,
           rot = 0.0;
    for (size_t i = 0; i < len; ++i) {
        double pitch = fabs(sdata.SLF_samples[i] * 2 / STD_AMPLITUDE);
        //printf("pitch: %lf rot: %lf\n", pitch, rot);
        sdata.VCO_samples[i] = STD_AMPLITUDE * sin(rot);
        rot += rot_angle * pitch;
        //printf("%f\n", sdata.VCO_samples[i]);
    }
}

void sound_event(uint8_t data)
{
    //printf("Revcd snd: 0x%02x\n", data);
    SDL_LockMutex(sdata_mutex);
    uint8_t oldvco = sdata.vco,
            oldon = sdata.on;
    sdata.data = (uint8_t)data;
    //printf("on:%d\n", !sdata.on);
    if (oldon != sdata.on)
        SDL_PauseAudioDevice(sdata.device_id, !sdata.on);
    if (oldvco != sdata.vco) {
        int freq_factor = VCO_IS(sdata.data & VCO_LOW_FREQ, VCO_HIGH_FREQ) ? 8 : 1;
        if (VCO_IS_SLF_CONTROLLED(sdata.data))
            generate_internal_vco(freq_factor);
        else
            generate_vco(freq_factor);
    }
    if (ENVELOPE_IS(sdata.data, ENVELOPE_ONE_SHOT))
        sdata.one_shot_state = OneShotArmed;

    SDL_UnlockMutex(sdata_mutex);
}

void sound_init()
{
	srand(time(NULL));

	SDL_InitSubSystem(SDL_INIT_AUDIO);

	SDL_AudioSpec spec = {
        .freq = SAMPLING_FREQ,
        .format = AUDIO_S16SYS,
        .channels = 1,
        .samples = SAMPLES_CNT,
        .callback = audio_callback
    };

	SDL_AudioDeviceID device_id = SDL_OpenAudioDevice(NULL, 0, &spec, NULL, 0);

    sdata_mutex = SDL_CreateMutex();
    SDL_LockMutex(sdata_mutex);
    sdata.spec = &spec;
    sdata.device_id = device_id;
    SDL_UnlockMutex(sdata_mutex);

	SDL_PauseAudioDevice(device_id, 1); // stop audio by default

    generate_slf();
}

void sound_destroy()
{
    SDL_DestroyMutex(sdata_mutex);
	SDL_Quit();
}
